source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/extremer/PrivatePodSpec.git'

use_frameworks!

target 'JJPrivatePod_Example' do
  pod 'JJPrivatePod', :path => '../'
  pod 'Alamofire'

  target 'JJPrivatePod_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
